/** @format */

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "TechVerse Events",
  description: "Generated by Hallas Lotfi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-background h-dvh w-full text-primary-txt`}
      >
        <div className="mx-auto h-full max-w-screen-2xl">{children}</div>
      </body>
    </html>
  );
}
